export type { IconProps } from "./types";
export { DEFAULT_ICON_SIZE, DEFAULT_ICON_COLOR } from "./types";

export {
  IconArrowRight,
  IconArrowLeft,
  IconArrowUp,
  IconArrowDown,
  IconChevronRight,
  IconChevronLeft,
  IconChevronUp,
  IconChevronDown,
  IconCheck,
  IconClose,
  IconPlus,
  IconMinus,
  IconSearch,
  IconMenu,
  IconMoreVertical,
  IconMoreHorizontal,
  IconInfo,
  IconWarning,
  IconError,
  IconSuccess,
  IconEye,
  IconEyeOff,
  IconSettings,
  IconCopy,
  IconTrash,
  IconEdit,
  IconExternalLink,
  IconLink,
  IconSun,
  IconMoon,
  IconGithub,
  IconTerminal,
  IconCode,
  IconPackage,
  IconCalendar,
  IconAim,
  IconRoute,
  IconCrossArrowsToRight,
  IconPlay,
  IconPause,
  IconTreeChart,
  IconClock,
} from "./common";

export {
  IconReact,
  IconPulse,
  IconVue,
  IconAngular,
  IconTypeScript,
  IconJavaScript,
} from "./other";
